// baseUrl = "http://localhost:8080/api-app/api";
baseUrl = "http://118.68.169.135:8080/api-app/api";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT = "LOGOUT";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";

export const CLAIM_INQUIRY_GET_POLICY_LIST = "CLAIM_INQUIRY_GET_POLICY_LIST";
export const CLAIM_INQUIRY_GET_POLICY_LIST_SUCCESS = "CLAIM_INQUIRY_GET_POLICY_LIST_SUCCESS";
export const CLAIM_INQUIRY_GET_POLICY_LIST_FAILED = "CLAIM_INQUIRY_GET_POLICY_LIST_FAILED";

export const CLAIM_INQUIRY_GET_CERTIFICATE_LIST = "CLAIM_INQUIRY_GET_CERTIFICATE_LIST";
export const CLAIM_INQUIRY_GET_CERTIFICATE_LIST_SUCCESS = "CLAIM_INQUIRY_GET_CERTIFICATE_LIST_SUCCESS";
export const CLAIM_INQUIRY_GET_CERTIFICATE_LIST_FAILED = "CLAIM_INQUIRY_GET_CERTIFICATE_LIST_FAILED";

export const CLAIM_INQUIRY_GET_CERTIFICATE_INFO = "CLAIM_INQUIRY_GET_CERTIFICATE_INFO";
export const CLAIM_INQUIRY_GET_CERTIFICATE_INFO_SUCCESS = "CLAIM_INQUIRY_GET_CERTIFICATE_INFO_SUCCESS";
export const CLAIM_INQUIRY_GET_CERTIFICATE_INFO_FAILED = "CLAIM_INQUIRY_GET_CERTIFICATE_INFO_FAILED";

export const CLAIM_INQUIRY_GET_CLAIM_BENEFIT_SUCCESS = "CLAIM_INQUIRY_GET_CLAIM_BENEFIT_SUCCESS";
export const CLAIM_INQUIRY_GET_CLAIM_BENEFIT_FAILED = "CLAIM_INQUIRY_GET_CLAIM_BENEFIT_FAILED";

export const CLAIM_HISTORY_GET_POLICY_LIST = "CLAIM_HISTORY_GET_POLICY_LIST";
export const CLAIM_HISTORY_GET_POLICY_LIST_SUCCESS = "CLAIM_HISTORY_GET_POLICY_LIST_SUCCESS";
export const CLAIM_HISTORY_GET_POLICY_LIST_FAILED = "CLAIM_HISTORY_GET_POLICY_LIST_FAILED";

export const CLAIM_HISTORY_GET_CERTIFICATE_LIST = "CLAIM_HISTORY_GET_CERTIFICATE_LIST";
export const CLAIM_HISTORY_GET_CERTIFICATE_LIST_SUCCESS = "CLAIM_HISTORY_GET_CERTIFICATE_LIST_SUCCESS";
export const CLAIM_HISTORY_GET_CERTIFICATE_LIST_FAILED = "CLAIM_HISTORY_GET_CERTIFICATE_LIST_FAILED";

export const CLAIM_HISTORY_GET_CERTIFICATE_INFO = "CLAIM_HISTORY_GET_CERTIFICATE_INFO";
export const CLAIM_HISTORY_GET_CERTIFICATE_INFO_SUCCESS = "CLAIM_HISTORY_GET_CERTIFICATE_INFO_SUCCESS";
export const CLAIM_HISTORY_GET_CERTIFICATE_INFO_FAILED = "CLAIM_HISTORY_GET_CERTIFICATE_INFO_FAILED";

export const CLAIM_HISTORY_GET_CLAIM_HISTORY_SUCCESS = "CLAIM_HISTORY_GET_CLAIM_HISTORY_SUCCESS";
export const CLAIM_HISTORY_GET_CLAIM_HISTORY_FAILED = "CLAIM_HISTORY_GET_CLAIM_HISTORY_FAILED";

export const HOSPITAL_GET_ADDRESS_DATA = "HOSPITAL_GET_ADDRESS_DATA";
export const HOSPITAL_GET_ADDRESS_DATA_SUCCESS = "HOSPITAL_GET_ADDRESS_DATA_SUCCESS";
export const HOSPITAL_GET_ADDRESS_DATA_FAILED = "HOSPITAL_GET_ADDRESS_DATA_FAILED";

export const HOSPITAL_ENQUIRY_DATA = "HOSPITAL_ENQUIRY_DATA";
export const HOSPITAL_ENQUIRY_DATA_SUCCESS = "HOSPITAL_ENQUIRY_DATA_SUCCESS";
export const HOSPITAL_ENQUIRY_DATA_FAILED = "HOSPITAL_ENQUIRY_DATA_FAILED";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";

export const SET_GLOBAL_INDICATOR_VISIBILITY = 'SET_GLOBAL_INDICATOR_VISIBILITY';