baseUrl = "http://localhost:8080/api-app/api";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT = "LOGOUT";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";

export const GET_POLICY_LIST = "GET_POLICY_LIST";
export const GET_POLICY_LIST_SUCCESS = "GET_POLICY_LIST_SUCCESS";
export const GET_POLICY_LIST_FAILED = "GET_POLICY_LIST_FAILED";

export const GET_CERTIFICATE_LIST = "GET_CERTIFICATE_LIST";
export const GET_CERTIFICATE_LIST_SUCCESS = "GET_CERTIFICATE_LIST_SUCCESS";
export const GET_CERTIFICATE_LIST_FAILED = "GET_CERTIFICATE_LIST_FAILED";

export const SET_GLOBAL_INDICATOR_VISIBILITY = 'SET_GLOBAL_INDICATOR_VISIBILITY';